# Generated by Django 5.2.14 on 2026-05-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='LocalEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=50, verbose_name='Local encontrado')),
            ],
            options={
                'verbose_name': 'Local Encontrado',
                'verbose_name_plural': 'Locais Encontrados',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.CharField(max_length=100, verbose_name='Email do usuário')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('tipo_usuario', models.CharField(max_length=30, verbose_name='Tipo de usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='ItemPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100, verbose_name='Nome do item')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_perda', models.DateField(verbose_name='Data da perda')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localencontrado', verbose_name='Local encontrado')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos',
            },
        ),
        migrations.CreateModel(
            name='ItemEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_encontrado', models.CharField(max_length=50, verbose_name='Local encontrado')),
                ('data_encontro', models.DateField(verbose_name='Data do encontro')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemperdido', verbose_name='Item perdido')),
            ],
            options={
                'verbose_name': 'Item Encontrado',
                'verbose_name_plural': 'Itens Encontrados',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(verbose_name='Data da devolução')),
                ('observacoes', models.CharField(max_length=255, verbose_name='Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemperdido', verbose_name='Item devolvido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
            },
        ),
    ]
